### PR TITLE
Each structured data output as a separate <script> tag.

### PR DESCRIPTION
**Pull request by thetoine**
Hello. I like your plugin concept, just nailed what I needed for creating special case per post or custom taxonomy.

Bunch of small commits :

- I refactored your output function so now each Structure Data block are outputted wrapped in a single <script> tag for each.
- Also, I cleaned the code a little bit, spacing wise, removed most tabs. Indentation still needs rework TBH.
- Date output was incorrect, must be in ISO 8601 format
- Finally, JSON output is printed using the flag JSON_PRETTY_PRINT

Thanks !

### CODE REVIEW

**Comment by ahmedkaludi** [comment]
@thetoine We will review this PR and get back to you.

**Comment by Sanjeevsetu** [comment]
Hi, 

Thanks for the input. Yeah date was in wrong format, We committed that in new ticket #35. We have few questions regarding your other commits

1. 7562887 - Why is it necessary to output each Structured Data block as a seperate <script> tag? We were doing so in past but now we have simplified in one single json array.

2. 67a8d40 - Why should we show json output pretty to users. I dont think it is necessary in production but we can use it in our development so it will be easy for developer to read.

**Comment by thetoine** [comment]
Hi @Sanjeevsetu !

Good for date format.

**1.**

Because the output is not valid. I changed it in the first place because the official [Google Validator](https://search.google.com/structured-data/testing-tool) was only detecting the first structured data block. With further investigation this morning, when using a single script tag, all objects should be wrapped in an array. Read here : https://stackoverflow.com/questions/30723531/best-json-ld-practices-using-multiple-script-elements/32954313#32954313

Check this capture from the validator. The source shows multiple structured data entities, only the first one is detected

image

And it make sense, the parser can't go pass the first entity because it's invalid JSON code anyway. The following code is valid. So it's either wrapper each bloc in an array, or like I did, each in a separate script tag.

```js
<script type="application/ld+json">
[
  {"@context":"http:\/\/schema.org","@type":"WebSite","id":"#website","url":"http:\/\/localhost:9900","name":"Today&#039;s Parks","potentialAction":{"@type":"SearchAction","target":"http:\/\/localhost:9900\/?s={search_term_string}","query-input":"required name=search_term_string"}},
  {"@context":"http:\/\/schema.org","@type":"Blogposting","mainEntityOfPage":"http:\/\/localhost:9900\/hello-world\/","headline":"Hello world!","description":"Welcome to WordPress. This is your first post. Edit or delete it, then start writing!","name":"Hello world!","url":"http:\/\/localhost:9900\/hello-world\/","datePublished":"septembre 13, 2018","dateModified":"septembre 13, 2018","author":{"@type":"Person","name":"admin"},"Publisher":{"@type":"Organization","logo":{"@type":"ImageObject","url":null,"width":null,"height":null},"name":"admin"},"image":{"@type":"ImageObject","url":null,"width":null,"height":null}},
  {"@context":"http:\/\/schema.org","@type":"Organization","name":"admin","url":null,"sameAs":[],"logo":{"@type":"ImageObject","url":null,"width":null,"height":null},"alternateName":"admin"}
]
</script>
```

**2.**

Mostly for debugging. But to be honest, I think HTML minify should happen at a higher level on all components, no just enabled for each components.

**Comment by Sanjeevsetu** [comment]
Hi @thetoine!

What you are saying, we are already doing. Again read my first point we are wrapping all objects in an array. You can check with my source code here. https://pastebin.com/VEkvptqa. All the schema are being detected by google testing tools. 
saswp-shot

**Comment by thetoine** [comment]
@Sanjeevsetu oups sorry, I read too fast! I wrote that after installing the latest version available on Wordpress.org, which is a version that still output without the array wrap.

All good then, I think you can close this PR now since you fixed the other things on your side.

**Comment by ahmedkaludi** [comment]
Thank you @thetoine

Your contributions means alot to us! I have even thank you on: http://structured-data-for-wp.com/2018/09/28/schema-structured-data-version-1-0-2-released/

Looking forward to more contributions.

**Pull request closed without merging**
